name: jbook
channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda-forge::jupytext
  - conda-forge::jupyter-book
  - conda-forge::myst-parser
  - conda-forge::pre-commit
  - pip
  - pip:
      - cookiecutter
    #   - sphinx-proof
