#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Research Notebook  # The title of the book. Will be placed in the left navbar.
author                      : J. Emmanuel Johnson  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : book.png  # A path to the book logo
# bibtex_reference_style: author_year 
execute:
  execute_notebooks: cache

# bibtex_bibfiles:
#     - references.bib
    # - content/notes/bayesian/bayesian.bib