#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Research Notebook  # The title of the book. Will be placed in the left navbar.
author                      : J. Emmanuel Johnson  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : book_v2.jpeg  # A path to the book logo
# bibtex_reference_style: author_year 
execute:
  execute_notebooks: "off"

repository:
  url                       : https://github.com/jejjohnson/research_notebook # Online location of your book
  path_to_book              : research_notebook  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# bibtex_bibfiles:
#   - references.bib
#   - bibliographies/software.bib

# BIBLIO
bibtex_bibfiles:
  - bibliographies/references.bib
  - bibliographies/software.bib
  - bibliographies/bayes.bib
  - bibliographies/blogs.bib
  - bibliographies/videos.bib
  - bibliographies/books.bib
  - bibliographies/spatiotemp.bib
  - bibliographies/kf.bib
  - bibliographies/dmm.bib
  - bibliographies/ssm.bib

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    bibtex_reference_style: author_year 
    # - content/notes/bayesian/bayesian.bib
  extra_extensions:
    - sphinx_proof
  #   - sphinx_togglebutton
    

# parse:
#   myst_enable_extensions:
#     # don't forget to list any other extensions you want enabled,
#     # including those that are enabled by default!
#     - mathtools
#     - html_image

launch_buttons:
  colab_url: "https://colab.research.google.com"